### ISSUE TITLE
New quotes don't show up

### ISSUE THREAD

**Issue by paulwalko** [anlutro/qdb#7]
After running everything on the readme, I tried running the test local server and after submitting, nothing was showing up.

**Comment by anlutro** [comment]
Hey! I haven't really explained how the application itself works in the readme. You should have set an admin password in the config.py file. Go to localhost:5000/login and log in with that, and you should see "Pending" in the top right - the quote should be there.

**Comment by paulwalko** [comment]
I see... thanks!
